"use client";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {readPsd,type Layer,type Psd} from "ag-psd";
import {FFmpeg} from "@ffmpeg/ffmpeg";
import {fetchFile} from "@ffmpeg/util";
import ffmpegCoreURL from "@ffmpeg/core?url";
import JSZip from "jszip";
import {ArrowDown,ArrowUp,AudioLines,ChevronDown,ChevronRight,Download,Eye,EyeOff,FileImage,FileMusic,FolderOpen,Layers3,Pause,Play,RotateCcw,ShieldCheck,Sparkles,Upload,Video,WandSparkles,ZoomIn} from "lucide-react";

type PL=Layer&{_id?:string;children?:PL[];canvas?:HTMLCanvasElement};
type Sprite="base"|"eyeOpen"|"eyeClosed"|"mouthClosed"|"mouthOpen";
type Pose="mouthOpen"|"mouthClosed"|"eyeOpen"|"eyeClosed";
const poseLabel:Record<Pose,string>={mouthOpen:"① 基本",mouthClosed:"② 口開け",eyeOpen:"③ 目開け",eyeClosed:"④ 目閉じ"};
const spriteLabel:Record<Sprite,string>={base:"基本の立ち絵",eyeOpen:"目：開き",eyeClosed:"目：閉じ",mouthClosed:"口：閉じ",mouthOpen:"口：開き"};
const fmt=(v:number)=>`${String(Math.floor(v/60)).padStart(2,"0")}:${(v%60).toFixed(1).padStart(4,"0")}`;
const leafIds=(l:PL):string[]=>l.children?.length?l.children.flatMap(leafIds):[l._id!];
const paintOrder=(items:PL[]):PL[]=>[...items].reverse().flatMap(l=>l.children?.length?paintOrder(l.children):[l]);
const blinkClosed=(t:number,timing:string)=>{const closed=.18;if(timing!=="random"){const gap=Number(timing);return t>=gap&&t%gap<closed}let next=0,i=1;while(next<=t){const random=Math.abs(Math.sin(i*12.9898)*43758.5453)%1;next+=4+random*6;if(t>=next&&t<next+closed)return true;i++}return false};
let currentLayerOrder:string[]=[];
let currentGroupRanks=new Map<string,number>();
function save(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

function LayerRow({l,d,selected,onToggle}:{l:PL;d:number;selected:Set<string>;onToggle:(l:PL)=>void}){
 const [open,setOpen]=useState(true),id=l._id!, kids=!!l.children?.length;
 const checked=kids?leafIds(l).some(x=>selected.has(x)):selected.has(id);
 const moveIds=leafIds(l),rank=currentGroupRanks.get(id)||0,managed=kids||d===0;
 return <><div className={`layer ${checked?"selected":""}`} style={{paddingLeft:8+d*14}}><button onClick={()=>kids&&setOpen(!open)}>{kids?(open?<ChevronDown/>:<ChevronRight/>):<i/>}</button><button className="visibility" onClick={()=>kids?setOpen(!open):onToggle(l)}>{checked?<Eye/>:<EyeOff/>}</button><span title={l.name} onClick={()=>kids?setOpen(!open):onToggle(l)}>{l.name||"名称なし"}</span>{managed&&<><b className="z-rank" title="親レイヤーの順位。1が最前面">#{String(rank).padStart(3,"0")}</b><div className="z-buttons group-order"><button title="親レイヤーを1つ前へ" onClick={()=>window.dispatchEvent(new CustomEvent("layer-move",{detail:{ids:moveIds,dir:1}}))}><ArrowUp/></button><button title="親レイヤーを1つ後ろへ" onClick={()=>window.dispatchEvent(new CustomEvent("layer-move",{detail:{ids:moveIds,dir:-1}}))}><ArrowDown/></button></div></>}<label className={`check ${kids?"parent-check":""}`} title={kids?"子パーツの選択状態":"表示する"}><input type="checkbox" checked={checked} disabled={kids} onChange={()=>!kids&&onToggle(l)}/><i/></label></div>{kids&&open&&l.children!.map(c=><LayerRow key={c._id} l={c} d={d+1} selected={selected} onToggle={onToggle}/>)}</>
}

export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),audio=useRef<HTMLAudioElement>(null),psd=useRef<Psd|null>(null),sprites=useRef<Partial<Record<Sprite,HTMLImageElement>>>({}),env=useRef(new Float32Array()),raf=useRef(0),playingRef=useRef(false);
 const [mode,setMode]=useState<"psd"|"png">("psd"),[psdName,setPsdName]=useState(""),[layers,setLayers]=useState<PL[]>([]),[layerOrder,setLayerOrder]=useState<string[]>([]),[poseTab,setPoseTab]=useState<Pose>("mouthOpen"),[poses,setPoses]=useState<Record<Pose,Set<string>>>({mouthOpen:new Set(),mouthClosed:new Set(),eyeOpen:new Set(),eyeClosed:new Set()}),[png,setPng]=useState<Partial<Record<Sprite,string>>>({});
 const [pendingPreset,setPendingPreset]=useState<{basic:string[];order:string[]}|null>(null),[presetTargets,setPresetTargets]=useState<Set<Pose>>(new Set(["mouthOpen"]));
 currentLayerOrder=layerOrder;
 currentGroupRanks=new Map();const rankGroups=(items:PL[])=>{const ordered=[...items].sort((a,b)=>Math.min(...leafIds(a).map(id=>layerOrder.indexOf(id)).filter(i=>i>=0))-Math.min(...leafIds(b).map(id=>layerOrder.indexOf(id)).filter(i=>i>=0)));ordered.forEach((g,i)=>currentGroupRanks.set(g._id!,ordered.length-i));items.forEach(g=>g.children&&rankGroups(g.children))};rankGroups(layers);
 const [audioName,setAudioName]=useState(""),[audioUrl,setAudioUrl]=useState(""),[duration,setDuration]=useState(0),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[blink,setBlink]=useState(true),[blinkTiming,setBlinkTiming]=useState("random"),[lip,setLip]=useState(true),[threshold,setThreshold]=useState(28),[scale,setScale]=useState(72),[x,setX]=useState(50),[y,setY]=useState(54),[res,setRes]=useState("1920x1080"),[fps,setFps]=useState(30),[status,setStatus]=useState("素材を読み込むと、ここにプレビューされます"),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0);
 const dims=useMemo(()=>res.split("x").map(Number),[res]),hasChar=mode==="psd"?!!psdName:Object.keys(png).length>0;
 const flatten=useCallback((a:PL[]):PL[]=>a.flatMap(v=>[v,...(v.children?flatten(v.children):[])]),[]);
 const ids=(a:PL[],p="l")=>a.forEach((v,i)=>{v._id=`${p}-${i}`;if(v.children)ids(v.children,v._id)});
 const draw=useCallback((t=time,out?:HTMLCanvasElement,forceAnimate=false,showBasic=false)=>{const c=out||canvas.current;if(!c)return;const[w,h]=dims;c.width=w;c.height=h;const q=c.getContext("2d",{alpha:true});if(!q)return;q.clearRect(0,0,w,h);const animating=forceAnimate||playingRef.current||!!out,n=Math.max(0,Math.min(env.current.length-1,Math.floor(t*60))),voiceLevel=Math.max(env.current[Math.max(0,n-2)]||0,env.current[n]||0,env.current[Math.min(env.current.length-1,n+2)]||0)*100,voiced=!showBasic&&lip&&voiceLevel>Math.max(3,threshold*.5),mouth=voiced&&Math.floor(t*8)%2===0,ending=duration>0&&t>=Math.max(0,duration-.3),eye=!showBasic&&blink&&!ending&&blinkClosed(t,blinkTiming);const sw=psd.current?.width||sprites.current.base?.naturalWidth||sprites.current.eyeOpen?.naturalWidth||1000,sh=psd.current?.height||sprites.current.base?.naturalHeight||sprites.current.eyeOpen?.naturalHeight||1000,k=Math.min(w/sw,h/sh)*scale/100;q.save();q.translate((w-sw*k)*x/100,(h-sh*k)*y/100);q.scale(k,k);
  if(mode==="psd"&&psd.current){let active:Set<string>;if(showBasic)active=new Set(poses.mouthOpen);else if(!animating)active=new Set(poses[poseTab]);else{active=new Set(poses.mouthOpen);const mouthDiff=new Set([...poses.mouthOpen,...poses.mouthClosed].filter(id=>poses.mouthOpen.has(id)!==poses.mouthClosed.has(id))),eyeDiff=new Set([...poses.eyeOpen,...poses.eyeClosed].filter(id=>poses.eyeOpen.has(id)!==poses.eyeClosed.has(id)));eyeDiff.forEach(id=>active.delete(id));const ep=eye?poses.eyeClosed:poses.eyeOpen;ep.forEach(id=>eyeDiff.has(id)&&active.add(id));mouthDiff.forEach(id=>active.delete(id));const mp=mouth?poses.mouthClosed:poses.mouthOpen;mp.forEach(id=>mouthDiff.has(id)&&active.add(id))}const map=new Map(paintOrder((psd.current.children||[]) as PL[]).map(l=>[l._id!,l]));layerOrder.forEach(id=>{const l=map.get(id);if(l&&active.has(id)&&l.canvas)q.drawImage(l.canvas,l.left||0,l.top||0)})}else{const p=(s:Sprite)=>{const i=sprites.current[s];if(i)q.drawImage(i,0,0,sw,sh)};p("base");p(eye?"eyeClosed":"eyeOpen");p(mouth?"mouthOpen":"mouthClosed")}q.restore()},[blink,blinkTiming,dims,duration,layerOrder,lip,mode,poseTab,poses,scale,threshold,time,x,y]);
 useEffect(()=>draw(),[draw]);
 const tick=useCallback(()=>{if(!audio.current)return;setTime(audio.current.currentTime);draw(audio.current.currentTime);if(!audio.current.paused)raf.current=requestAnimationFrame(tick)},[draw]);
 useEffect(()=>{const el=audio.current;if(!el)return;const ended=()=>{playingRef.current=false;setPlaying(false);cancelAnimationFrame(raf.current);draw(el.duration||el.currentTime,undefined,true,true)};el.addEventListener("ended",ended);return()=>el.removeEventListener("ended",ended)},[draw]);
 const play=async()=>{if(!audio.current||!audioUrl)return;if(audio.current.paused){audio.current.muted=false;audio.current.volume=1;playingRef.current=true;setPlaying(true);await audio.current.play();raf.current=requestAnimationFrame(tick)}else{audio.current.pause();playingRef.current=false;setPlaying(false);cancelAnimationFrame(raf.current);draw(audio.current.currentTime,undefined,true)}};
 const loadPsd=async(f:File)=>{try{setStatus("PSDのレイヤーを解析しています…");const p=readPsd(await f.arrayBuffer(),{skipThumbnail:true,useImageData:false}),ch=(p.children||[]) as PL[];ids(ch);psd.current=p;setLayers(ch);setLayerOrder(paintOrder(ch).map(l=>l._id!));setPsdName(f.name);setMode("psd");const initial=new Set(flatten(ch).filter(l=>!l.hidden).map(l=>l._id!));setPoses({mouthOpen:new Set(initial),mouthClosed:new Set(initial),eyeOpen:new Set(initial),eyeClosed:new Set(initial)});setStatus("矢印で各パーツの前後関係を変更できます")}catch(e){console.error(e);setStatus("PSDを読み込めません。RGB/8bitで保存し直してください")}};
 const loadPng=(key:Sprite,f:File)=>{const i=new Image;i.onload=()=>{sprites.current[key]=i;setPng(v=>({...v,[key]:f.name}));setMode("png");setStatus("PNGパーツを読み込みました")};i.src=URL.createObjectURL(f)};
 const loadAudio=async(f:File)=>{try{setStatus("音声を解析しています…");const u=URL.createObjectURL(f);setAudioUrl(u);setAudioName(f.name);const ac=new AudioContext,b=await ac.decodeAudioData(await f.arrayBuffer()),d=b.getChannelData(0),frames=Math.ceil(b.duration*60),raw=new Float32Array(frames);for(let i=0;i<frames;i++){const s=Math.floor(i*b.sampleRate/60),z=Math.min(d.length,Math.floor((i+1)*b.sampleRate/60));let sum=0;for(let j=s;j<z;j++)sum+=d[j]*d[j];raw[i]=Math.sqrt(sum/Math.max(1,z-s))}const sorted=Array.from(raw).sort((a,b)=>a-b),noise=(sorted[Math.floor(sorted.length*.15)]||0)*1.5,peak=sorted[Math.floor(sorted.length*.98)]||1,e=new Float32Array(frames),span=Math.max(.0001,peak-noise);for(let i=0;i<frames;i++)e[i]=Math.max(0,Math.min(1,(raw[i]-noise)/span));env.current=e;setDuration(b.duration);await ac.close();setStatus("音声解析が完了しました")}catch{setStatus("音声を読み込めませんでした")}};
 const togglePose=(l:PL)=>{if(l.children?.length)return;setPoses(v=>{const next={...v,[poseTab]:new Set(v[poseTab])},set=next[poseTab];set.has(l._id!)?set.delete(l._id!):set.add(l._id!);return next})};
 const saveBasicPreset=()=>{if(!layers.length){setStatus("先にPSDを読み込んでください");return}const data={format:"zunda-motion-basic-preset",version:1,psdName,basicLayerIds:[...poses.mouthOpen],layerOrder:[...layerOrder],layers:flatten(layers).map(l=>({id:l._id,name:l.name||"名称なし"}))},name=(psdName.replace(/\.psd$/i,"")||"character")+"-basic-preset.json";save(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),name);setStatus("①基本のプリセットを保存しました")};
 const loadBasicPreset=async(f:File)=>{try{if(!layers.length)throw new Error("PSD_REQUIRED");const data=JSON.parse(await f.text()) as {format?:string;basicLayerIds?:unknown;layerOrder?:unknown};if(data.format!=="zunda-motion-basic-preset"||!Array.isArray(data.basicLayerIds)||!Array.isArray(data.layerOrder))throw new Error("INVALID");const valid=new Set(paintOrder(layers).map(l=>l._id!)),basic=data.basicLayerIds.filter((id):id is string=>typeof id==="string"&&valid.has(id)),ordered=data.layerOrder.filter((id):id is string=>typeof id==="string"&&valid.has(id)),used=new Set(ordered),rest=layerOrder.filter(id=>!used.has(id));setPendingPreset({basic,order:[...ordered,...rest]});setPresetTargets(new Set(["mouthOpen"]));setStatus("設定を適用する状態を選択してください")}catch(e){setStatus(e instanceof Error&&e.message==="PSD_REQUIRED"?"先に対応するPSDを読み込んでください":"プリセットを読み込めませんでした")}};
 const togglePresetTarget=(p:Pose)=>setPresetTargets(v=>{const next=new Set(v);next.has(p)?next.delete(p):next.add(p);return next});
 const applyBasicPreset=()=>{if(!pendingPreset||!presetTargets.size){setStatus("適用先を1つ以上選択してください");return}setPoses(v=>{const next={...v};presetTargets.forEach(p=>next[p]=new Set(pendingPreset.basic));return next});setLayerOrder(pendingPreset.order);const first=(Object.keys(poseLabel) as Pose[]).find(p=>presetTargets.has(p));if(first)setPoseTab(first);setPendingPreset(null);setStatus("選択した状態に設定を読み込みました")};
 const moveLayer=(ids:string[],dir:number)=>setLayerOrder(v=>{const wanted=new Set(ids);const same=(g:PL)=>{const a=leafIds(g);return a.length===wanted.size&&a.every(id=>wanted.has(id))};const find=(items:PL[]):PL[]|null=>{if(items.some(same))return items;for(const item of items){if(item.children){const hit=find(item.children);if(hit)return hit}}return null};const siblings=find(layers);if(!siblings)return v;const groups=[...siblings].sort((a,b)=>Math.min(...leafIds(a).map(id=>v.indexOf(id)).filter(i=>i>=0))-Math.min(...leafIds(b).map(id=>v.indexOf(id)).filter(i=>i>=0))),at=groups.findIndex(same),to=Math.max(0,Math.min(groups.length-1,at+dir));if(at<0||at===to)return v;[groups[at],groups[to]]=[groups[to],groups[at]];const used=new Set(groups.flatMap(leafIds)),positions=[...used].map(id=>v.indexOf(id)).filter(i=>i>=0),start=Math.min(...positions),before=v.slice(0,start).filter(id=>!used.has(id)),after=v.slice(start).filter(id=>!used.has(id)),ordered=groups.flatMap(g=>{const set=new Set(leafIds(g));return v.filter(id=>set.has(id))});return [...before,...ordered,...after]});
 useEffect(()=>{const handler=(e:Event)=>{const {ids,dir}=(e as CustomEvent<{ids:string[];dir:number}>).detail;moveLayer(ids,dir)};window.addEventListener("layer-move",handler);return()=>window.removeEventListener("layer-move",handler)},[layers]);
 const webm=async()=>{if(!hasChar||!audioUrl||!canvas.current){setStatus("立ち絵と音声を先に読み込んでください");return}setExporting(true);setProgress(0);setStatus("透過WebMを書き出しています（音声の長さだけ待ちます）");const stream=canvas.current.captureStream(fps),a=new Audio(audioUrl),ac=new AudioContext,src=ac.createMediaElementSource(a),dest=ac.createMediaStreamDestination();src.connect(dest);dest.stream.getAudioTracks().forEach(t=>stream.addTrack(t));const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm",r=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:12000000}),chunks:Blob[]=[];r.ondataavailable=e=>e.data.size&&chunks.push(e.data);r.onstop=async()=>{save(new Blob(chunks,{type:mime}),"zunda-motion-alpha.webm");await ac.close();setExporting(false);setProgress(100);setStatus("透過WebMを書き出しました")};r.start(500);await a.play();const loop=()=>{draw(a.currentTime,undefined,true);setProgress(Math.min(99,a.currentTime/duration*100));a.ended?r.stop():requestAnimationFrame(loop)};loop()};
 const mov=async()=>{if(!hasChar||!audioUrl||!duration){setStatus("立ち絵と音声を先に読み込んでください");return}setExporting(true);setProgress(0);const ffmpeg=new FFmpeg;let wasmURL="";try{setStatus("MOV変換エンジンを読み込んでいます…");const parts=await Promise.all(["aa","ab","ac"].map(async p=>{const r=await fetch(new URL(`ffmpeg/ffmpeg-core.wasm.${p}`,document.baseURI));if(!r.ok)throw new Error("変換エンジンを取得できません");return r.arrayBuffer()}));wasmURL=URL.createObjectURL(new Blob(parts,{type:"application/wasm"}));ffmpeg.on("progress",({progress})=>setProgress(70+Math.max(0,Math.min(1,progress))*29));await ffmpeg.load({coreURL:ffmpegCoreURL,wasmURL});const count=Math.ceil(duration*fps),off=document.createElement("canvas");setStatus("透過MOV用のフレームを作成しています…");for(let i=0;i<count;i++){draw(i/fps,off);const blob=await new Promise<Blob|null>(r=>off.toBlob(r,"image/png"));if(blob)await ffmpeg.writeFile(`frame_${String(i).padStart(6,"0")}.png`,await fetchFile(blob));if(i%4===0){setProgress(i/count*68);await new Promise(r=>setTimeout(r,0))}}await ffmpeg.writeFile("audio.wav",await fetchFile(audioUrl));setStatus("音声付き透過MOVに変換しています…");await ffmpeg.exec(["-framerate",String(fps),"-i","frame_%06d.png","-i","audio.wav","-c:v","prores_ks","-profile:v","4","-pix_fmt","yuva444p10le","-c:a","pcm_s16le","-shortest","zunda-motion-alpha.mov"]);const data=await ffmpeg.readFile("zunda-motion-alpha.mov");if(typeof data==="string")throw new Error("MOV生成に失敗しました");save(new Blob([data.slice().buffer],{type:"video/quicktime"}),"zunda-motion-alpha.mov");setProgress(100);setStatus("音声付き透過MOVを書き出しました")}catch(e){console.error(e);setStatus("MOVを書き出せませんでした。短い音声または低い解像度で再度お試しください")}finally{ffmpeg.terminate();if(wasmURL)URL.revokeObjectURL(wasmURL);setExporting(false)}};
 const sequence=async()=>{if(!hasChar||!duration){setStatus("立ち絵と音声を先に読み込んでください");return}setExporting(true);setProgress(0);setStatus("DaVinci用PNG連番を作成しています…");const zip=new JSZip(),count=Math.ceil(duration*fps),off=document.createElement("canvas");for(let i=0;i<count;i++){draw(i/fps,off);const b=await new Promise<Blob|null>(r=>off.toBlob(r,"image/png"));if(b)zip.file(`frames/zunda_${String(i).padStart(6,"0")}.png`,b);if(i%8===0){setProgress(i/count*100);await new Promise(r=>setTimeout(r,0))}}zip.file(`audio/${audioName}`,await fetch(audioUrl).then(r=>r.blob()));zip.file("README.txt",`DaVinci Resolveで最初のPNGを画像シーケンスとして読み込んでください。\nFPS: ${fps}\n解像度: ${res}\n背景: 透過`);save(await zip.generateAsync({type:"blob",compression:"DEFLATE"}),"zunda-motion-davinci.zip");setExporting(false);setProgress(100);setStatus("透過PNG連番と音声を書き出しました")};
 const bars=useMemo(()=>Array.from({length:64},(_,i)=>env.current.length?Math.max(5,env.current[Math.floor(i/64*env.current.length)]*42):8+(i*13)%20),[audioName]);
 return <main className="app"><header><div className="brand"><b><AudioLines/></b><div><strong>ずんだモーション</strong><small>STUDIO</small></div></div><div className="project"><i/>新規プロジェクト <span>自動保存なし</span></div><div className="privacy"><ShieldCheck/>ファイルは端末内だけで処理</div></header>
 <section className="work"><aside className="panel left"><Title n="01 / ASSETS" text="素材" icon={<FolderOpen/>}/><div className="tabs"><button className={mode==="psd"?"on":""} onClick={()=>setMode("psd")}>PSD</button><button className={mode==="png"?"on":""} onClick={()=>setMode("png")}>PNG</button></div>{mode==="psd"?<><label className={`drop ${psdName?"loaded":""}`}><input type="file" accept=".psd" onChange={e=>e.target.files?.[0]&&loadPsd(e.target.files[0])}/>{psdName?<><FileImage/><strong>{psdName}</strong><span>{flatten(layers).length} レイヤー</span></>:<><Upload/><strong>PSDを開く</strong><span>内部レイヤーを直接読み取ります</span></>}</label>{!!layers.length&&<div className="tree"><h3><Layers3/>状態ごとのPSDパーツ</h3><div className="pose-tabs">{(Object.keys(poseLabel) as Pose[]).map(p=><button key={p} className={poseTab===p?"on":""} onClick={()=>setPoseTab(p)}>{poseLabel[p]}</button>)}</div><div className="preset-actions"><button onClick={saveBasicPreset}><Download/>①基本の設定を保存</button><label><input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)loadBasicPreset(f);e.currentTarget.value=""}}/><Upload/>設定の読込</label></div>{pendingPreset&&<div className="preset-targets"><strong>設定を適用する状態</strong><div>{(Object.keys(poseLabel) as Pose[]).map(p=><label key={p}><input type="checkbox" checked={presetTargets.has(p)} onChange={()=>togglePresetTarget(p)}/><span>{poseLabel[p]}</span></label>)}</div><footer><button onClick={()=>setPendingPreset(null)}>キャンセル</button><button className="apply" onClick={applyBasicPreset}>選択した状態に適用</button></footer></div>}<p className="pose-help">「{poseLabel[poseTab]}」で表示するパーツにチェック</p>{layers.map(l=><LayerRow key={l._id} l={l} d={0} selected={poses[poseTab]} onToggle={togglePose}/>)}</div>}</>:<div className="slots">{(["base","eyeOpen","eyeClosed","mouthClosed","mouthOpen"] as Sprite[]).map((s,i)=><label className={png[s]?"filled":""} key={s}><input type="file" accept="image/png" onChange={e=>e.target.files?.[0]&&loadPng(s,e.target.files[0])}/><em>{String(i+1).padStart(2,"0")}</em><FileImage/><div><strong>{spriteLabel[s]}</strong><small>{png[s]||"PNGを選択"}</small></div></label>)}</div>}</aside>
 <section className="center"><div className="tools"><span>PREVIEW</span><div><button onClick={()=>setScale(v=>Math.max(20,v-5))}>−</button><b>{scale}%</b><button onClick={()=>setScale(v=>Math.min(150,v+5))}><ZoomIn/></button><button onClick={()=>{setScale(72);setX(50);setY(54)}}><RotateCcw/></button></div></div><div className="stage"><canvas ref={canvas}/>{!hasChar&&<label className="empty"><WandSparkles/><strong>立ち絵を読み込んでください</strong><span>PSDまたは透過PNGに対応</span><input type="file" accept=".psd" onChange={e=>e.target.files?.[0]&&loadPsd(e.target.files[0])}/><b>PSDを選択</b></label>}<label className="alpha"><i/>TRANSPARENT</label></div><div className="transport"><button className="play" onClick={play} disabled={!audioUrl}>{playing?<Pause/>:<Play/>}</button><div className="clock"><b>{fmt(time)}</b><span>/ {fmt(duration)}</span></div><div className="wave" onClick={e=>{const r=e.currentTarget.getBoundingClientRect(),t=(e.clientX-r.left)/r.width*duration;if(audio.current)audio.current.currentTime=t;setTime(t);draw(t)}}>{bars.map((h,i)=><i key={i} style={{height:h}}/>)}<b style={{left:`${duration?time/duration*100:0}%`}}/></div><label className={`audio ${audioName?"ready":""}`}><input type="file" accept="audio/wav,audio/mpeg,.wav,.mp3" onChange={e=>e.target.files?.[0]&&loadAudio(e.target.files[0])}/><FileMusic/><span>{audioName||"WAVを追加"}</span></label><audio ref={audio} src={audioUrl} onEnded={()=>setPlaying(false)}/></div></section>
 <aside className="panel right"><Title n="02 / MOTION" text="動き" icon={<Sparkles/>}/><Setting icon={<AudioLines/>} title="自動口パク" sub="音量に合わせて開閉" on={lip} toggle={()=>setLip(!lip)}><Range name="反応しやすさ" value={threshold} set={setThreshold} min={5} max={70}/></Setting><Setting icon={<Eye/>} title="自動まばたき" sub="間隔を指定、またはランダム" on={blink} toggle={()=>setBlink(!blink)}><label className="blink-timing"><span>まばたき間隔</span><select value={blinkTiming} onChange={e=>setBlinkTiming(e.target.value)}><option value="random">ランダム（4〜10秒）</option>{Array.from({length:10},(_,i)=><option key={i+1} value={String(i+1)}>{i+1}秒</option>)}</select></label></Setting><div className="card compact"><h3>配置</h3><Range name="横位置" value={x} set={setX}/><Range name="縦位置" value={y} set={setY}/><Range name="大きさ" value={scale} set={setScale} min={20} max={150}/></div><div className="export"><div className="export-title"><Video/><div><strong>書き出し</strong><span>背景は常に透明です</span></div></div><div className="opts"><label>解像度<select value={res} onChange={e=>setRes(e.target.value)}><option>1920x1080</option><option>1280x720</option><option>3840x2160</option></select></label><label>FPS<select value={fps} onChange={e=>setFps(+e.target.value)}><option>30</option><option>60</option></select></label></div><button className="primary" disabled={exporting} onClick={mov}><Download/>{exporting?`処理中 ${Math.round(progress)}%`:"音声付き透過MOVを書き出す"}</button><button className="secondary" disabled={exporting} onClick={webm}>透過WebMを書き出す</button><button className="secondary" disabled={exporting} onClick={sequence}>DaVinci用 PNG連番 + WAV</button><p>MOVはProRes 4444・音声付きで書き出します。長い音声や4Kはメモリを多く使用します。</p></div></aside></section><footer><i/><span>{status}</span><div><span>{res}</span><span>{fps} FPS</span><span>RGBA</span></div></footer></main>
}
function Title({n,text,icon}:{n:string;text:string;icon:React.ReactNode}){return <div className="title"><div><small>{n}</small><h2>{text}</h2></div>{icon}</div>}
function Range({name,value,set,min=0,max=100}:{name:string;value:number;set:(v:number)=>void;min?:number;max?:number}){return <label className="range"><span>{name}<b>{value}%</b></span><input type="range" min={min} max={max} value={value} onChange={e=>set(+e.target.value)}/></label>}
function Setting({icon,title,sub,on,toggle,children}:{icon:React.ReactNode;title:string;sub:string;on:boolean;toggle:()=>void;children?:React.ReactNode}){return <div className="card"><div className="setting"><b>{icon}</b><div><strong>{title}</strong><span>{sub}</span></div><button className={on?"switch on":"switch"} onClick={toggle}><i/></button></div>{children}</div>}
